addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")
addSbtPlugin("com.47deg" % "sbt-microsites" % "1.0.1")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.0.2")
