addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.0") 
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")
addSbtPlugin("com.47deg"  % "sbt-microsites" % "0.9.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "1.3.1" )